### ISSUE TITLE
Corriger (le tri) des listes de candidats

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#67]
RESULTS OF MATCHING
Cette liste comprend tous les candidat appartenant au district électoral, qui ont répondu à au moins une question, parmi celles que l'utilisateur à rempli. 
Sorted in decreasing order of score. Next criteria= level of completeness of profile. Next sort criteria is the place on the roll. 

LIST OF CANDIDATES (after input of postcode, when there are no 6 respondants):
Cette liste comprend deux catégories de candidats (de la commune):
- ceux qui ont répondu à au moins une question du questionnaire GPS  (en noir)
- ceux qui n'ont pas répondu du tout, mais dont le "level of completeness" >12%  (en grisé)
First criteria: number of questions answered by the candidate
Second: completeness of profile

**Comment by Damiendv** [comment]
Sur Ixelles, je recois le message qu'il y a moins de 6 candidats. Le profile de la Bourgemestre actuelle, Dominique Defourny, est grisé. Quand je clique sur son profile, je vois néanmoins qu'elle a répondu à plein de questions communales le 29/09/2018. Est-ce normal? Nous avions décidé de quand même intégrer les gens qui avaient répondus à quelques questions. Quand est-ce que celà sera opérationnel? Merci!

![image](https://user-images.githubusercontent.com/43785103/46593722-7cc29200-cace-11e8-9ec9-5862a8c95999.png)

![image](https://user-images.githubusercontent.com/43785103/46593739-995eca00-cace-11e8-896a-9193a7ce350b.png)

**Comment by Damiendv** [comment]
Sur Boitsfort, il y a 6 candidats en noir mais on ne peut pas faire le test. A-t-on augmenté le seuil de 6 à plus?

![image](https://user-images.githubusercontent.com/43785103/46607845-bdd49980-cb02-11e8-99bd-9381a1cefe17.png)

**Comment by danielsum** [comment]
Coucou Damien,

Oui la condition c’est plus grand que 6 => on peut faire >= à 6 s’il faut.

Dan


Le 8 octobre 2018 à 14:02:23, Damiendv (notifications@github.com) a écrit:

Sur Boitsfort, il y a 6 candidats en noir mais on ne peut pas faire le
test. A-t-on augmenté le seuil de 6 à plus?

[image: image]
<https://user-images.githubusercontent.com/43785103/46607845-bdd49980-cb02-11e8-99bd-9381a1cefe17.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wecitizens/electoral-gps-frontend/issues/67#issuecomment-427807428>,
or mute the thread

**Comment by JPPinon** [comment]
C'est ce que nous avons annoncé dans le communiqué de presse: >=6
