### ISSUE TITLE
Add newsletter popup

### ISSUE THREAD

**Issue by Damiendv** [wecitizens/electoral-gps-frontend#69]
Merci aux devs pour le travail acharné! @danielsum  @olivier5741 

L'objectif du GPS électoral pour les communales est de nous aider à avoir un plus grand impact aux élections fédérales/régionales/EU. Tout le développement que vous avez fait pour les communales est déjà engrangé et c'est super. Je pense qu'il serait encore à notre portée de nous aider davantage pour les fédérales en cherchant au augmenter la user base potentielle en proposant aux utilisateurs de s'inscrire à la Newsletter.

Pourriez-vous rajouter la page pop-up d'inscription à la Newsletter prévue dans les Wireframes, après les résultats? Ou au moins un bouton pop-up simple avec le message "WeCitizens travaille dur pour vous fournir un outil plus performant aux élections de mai 2019. Inscrivez-vous à notre newsletter pour être tenu au courant et faire un vote informé"? Merci!

En Anglais: "WeCitizens is working hard to develop a more performing tool for the May 2019 elections. Register to our newsletter to be kepts informed and cast an informed vote"
En NL: "WijBurgers werkt hart aan een betere app voor de Mei 2019 verkiezingen. Schrijf jij op onze newsletter om ervan op de hoogte te blijven en geïnformeerd te stemmen"

@JPPinon , peux-tu stp vérifier la traduction NL? Merci

![image](https://user-images.githubusercontent.com/43785103/46546370-1caece80-c8c9-11e8-8ad7-3f77005c3edc.png)

**Comment by olivier5741** [comment]
Ok in prod

**Comment by Damiendv** [comment]
Merci ! Je viens de faire le test et je n'ai pas eu de pop-up. A quel moment l'avez vous fait intervenir ? Ou est-ce déjà publié ?

**Comment by danielsum** [comment]
C’est publié sur Demo et prod normalement ?

Moi je l’ai bien => tu as raffraichi ta cache ?

Dan

Le 11 octobre 2018 à 09:56:32, Damiendv (notifications@github.com) a écrit:

Merci ! Je viens de faire le test et je n'ai pas eu de pop-up. A quel
moment l'avez vous fait intervenir ? Ou est-ce déjà publié ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wecitizens/electoral-gps-frontend/issues/69#issuecomment-428857846>,
or mute the thread
