### ISSUE TITLE
Bug results NaN% candidates + double ":"

### ISSUE THREAD

**Issue by Damiendv** [wecitizens/electoral-gps-frontend#78]
Sur Ixelles, je vois deux candidats dans les résultats qui s'affichents comme NaN%. Aussi, dans l'intitulé, il y a deux ":" d'affilé.

C'est peut-etre un problème de cache/cookies. Ca peut dans tous les cas etre problématique pour les usagers qui reviennent d'un jour à l'autre à l'application pour avoir un meilleur test (comme on leur invite de faire sur la "insufficient candidate" page)

![image](https://user-images.githubusercontent.com/43785103/46684246-8c3afb80-cbf2-11e8-9248-f93bbf1ba618.png)

**Comment by olivier5741** [comment]
Seems ok in demo and prod now (Daniel pushed 20 minutes ago)

**Comment by Damiendv** [comment]
J'ai fait le test ce matin sur Ixelles; 9 questions répondues au hasard, pas rempli les champs statistiques et je retrouve les NaN%. J'amais clearé mon cache

Aussi, je remarque que je suis en http et pas en httpS. C'est peut-etre ca?

![image](https://user-images.githubusercontent.com/43785103/46791669-eb5b5600-cd41-11e8-9411-e16cbb34d4fb.png)

**Comment by danielsum** [comment]
Tu dois absolument effacer ta cache, à mon avis t’as encore une très
ancienne version.

Tu peux checker sur un autre navigateur ?

Si le cache est effacé => tu devrais avoir Newsletter dans le menu principal

Le 11 octobre 2018 à 10:40:13, Damiendv (notifications@github.com) a écrit:

J'ai fait le test ce matin sur Ixelles; 9 questions répondues au hasard,
pas rempli les champs statistiques et je retrouve les NaN%. J'amais clearé
mon cache

Aussi, je remarque que je suis en http et pas en httpS. C'est peut-etre ca?

[image: image]
<https://user-images.githubusercontent.com/43785103/46791669-eb5b5600-cd41-11e8-9411-e16cbb34d4fb.png>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/wecitizens/electoral-gps-frontend/issues/78#issuecomment-428870664>,
or mute the thread

**Comment by Damiendv** [comment]
J'ai essayé depuis un autre navigateur et ca marche. Merci. 

Il n'est pas possible de "overwrite" la cache de l'utilisateur? Nous encourageons les gens à revenir sur le site et ne pouvons pas nous attendre à ce qu'ils "clear" leur cache ou utiliser un autre navigateur à chaque fois.

**Comment by danielsum** [comment]
La cache est au niveau DNS...

Pour ne pas trop rentrer dans le détail => c’est à un niveau qu’on ne peut
malheureusement pas controller :/.

=> il faudrait qu’on ait un plein accès au nom de domaine et qu’on puisse
installer un système de cache comme Cloudflare pour ça.

Dan


Le 11 octobre 2018 à 10:59:49, Damiendv (notifications@github.com) a écrit:

J'ai essayé depuis un autre navigateur et ca marche. Merci.

Il n'est pas possible de "overwrite" la cache de l'utilisateur? Nous
encourageons les gens à revenir sur le site et ne pouvons pas nous attendre
à ce qu'ils "clear" leur cache ou utiliser un autre navigateur à chaque
fois.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/wecitizens/electoral-gps-frontend/issues/78#issuecomment-428876952>,
or mute the thread

**Comment by JPPinon** [comment]
@danielsum : quand tu dis que tu aurais besoin d'avoir accès au nom de domaine pour installer p.ex. Cloudflare, tu vise l'hébergeur (Saad) ou le Registrar (M. Ooms) ? Ils sont tous deux accessibles.

**Comment by olivier5741** [comment]
The topic changed, I close the issue
