### ISSUE TITLE
erreur dans la traduction

### ISSUE THREAD

**Issue by JPPinon** [wecitizens/electoral-gps-frontend#80]
Dans le questionnaire en NL, il est affiché "tout à fait d'accord" en FR !
J'ai corrigé le Translation file, à la ligne 94. IL faut faire un refresh.
(Il y a trois lignes pour la même expression, dans ce tableau...)

**Comment by JPPinon** [comment]
@danielsum 
un problèms "linguistique" se précise (au fil des plaintes reçues, en flamand):
des gens sont sur la page d'accueil NL, Ils cliquent sur "Test" et l'application poursuit en FR

**Comment by olivier5741** [comment]
Seems ok in prod both `tout à fait d'accord` translation and language hop

**Comment by JPPinon** [comment]
@danielsum @olivier5741 
J'ai vider mon "cache". Les modifications d'hier dans le fichier "Translation" ne sont pas prises en compte.
![image](https://user-images.githubusercontent.com/43548775/46804569-45204800-cd63-11e8-95fe-ca263b23bd37.png)

**Comment by danielsum** [comment]
Chez moi c’est bien correct => pour checker il faut aller dans menu (si
vous voyez Newsletter c’est que l’app a été mis à jour).

=> c’est assez pénible qu’on ne puisse pas ni sync la db, ni mettre à jour
la cache DNS (avoir accès au nom de domaine)... => à discuter mais ce genre
de chose ralentit très fortement le dév (je passe la plupart du temps à
faire des synchros manuelles, à essayer de trouver des astuces pour
extraire les données du poldir, ou à devoir trouver des solutions tech…).
Il faudra faire une réunion de débriefing par rapport à ça rapidement.

Dan




Le 11 octobre 2018 à 14:38:19, JPPinon (notifications@github.com) a écrit:

Reopened #80
<https://github.com/wecitizens/electoral-gps-frontend/issues/80>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wecitizens/electoral-gps-frontend/issues/80#event-1898084434>,
or mute the thread
